/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chira
 */
public class Transfer extends javax.swing.JInternalFrame {

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement st1;
    PreparedStatement st2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtamount = new javax.swing.JTextField();
        txttoacc = new javax.swing.JTextField();
        txtbalance = new javax.swing.JTextField();
        txtfromacc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Transfer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));

        txtamount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 189, -1));

        txttoacc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txttoacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttoaccActionPerformed(evt);
            }
        });
        getContentPane().add(txttoacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 189, -1));

        txtbalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalanceActionPerformed(evt);
            }
        });
        getContentPane().add(txtbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 189, -1));

        txtfromacc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtfromacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 189, -1));

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Balance");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To Account");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount Transfer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/transfer.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            String fromaccount = txtfromacc.getText();
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/bankdatabase","root","Chir@g244724");
            pst = con.prepareStatement("select * from account where accountid = ?");
            pst.setString(1, fromaccount);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next() == false)
            {
                JOptionPane.showMessageDialog(this, "Account Id not Found", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txtfromacc.setText("");
                    txtfromacc.requestFocus();
            }
            else
            {
                String balance = rs.getString("balance");
                
                txtbalance.setText(balance.trim());
                
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
            // TODO add your handling code here:
            
            String facc = txtfromacc.getText();        
            String bal = txtbalance.getText();
            String tacc = txttoacc.getText();
            String amount = txtamount.getText();
            
            int b = Integer.parseInt(bal);
            int a = Integer.parseInt(amount);
            
            if(b < a)
            {
                JOptionPane.showMessageDialog(this, "Insufficient Amount.......");
                txtfromacc.setText("");
                txtbalance.setText("");
                txttoacc.setText("");
                txtamount.setText("");
                txtfromacc.requestFocus();
                
            }
            else
            {
                try {
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/bankdatabase","root","Chir@g244724");
            
            con.setAutoCommit(false);
            
            //sender
            st1 = con.prepareStatement("update account set balance = balance - ? where accountid = ?");
            st1.setString(1, amount);
            st1.setString(2, facc);
            st1.executeUpdate();
            
            //receiver
            st2 = con.prepareStatement("update account set balance = balance + ? where accountid = ?");
            st2.setString(1, amount);
            st2.setString(2,tacc);
            st2.executeUpdate();
            
            
            pst = con.prepareStatement("insert into transfer(fromaccount, toaccount, amount)values(?,?,?)");
            pst.setString(1, facc);
            pst.setString(2,tacc);
            pst.setString(3,amount);
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Amount Transfered.......");
            con.commit();
            
            txtfromacc.setText("");
            txtbalance.setText("");
            txttoacc.setText("");
            txtamount.setText("");
            txtfromacc.requestFocus();
            
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            try {
                con.rollback();
                Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex1) {
                Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalanceActionPerformed

    private void txttoaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttoaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttoaccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtfromacc;
    private javax.swing.JTextField txttoacc;
    // End of variables declaration//GEN-END:variables
}
